from django.contrib import admin
from . models import User, Origin, TowCarOwner, Store, storeBrands, TowRequest, Images, Brand,  maintenance, RequestType, WorkShop, WorkShopOwner, TowCars, TowBrand, TowOrigin, CarModel, location, CarOwner, Product, TransactionStatus, Status, PartSupplier, ProductPartSupplier, Cars, Specialist, workshopBrands, location, City, Request

admin.site.register(User)
admin.site.register(Origin)
admin.site.register(Brand)
admin.site.register(WorkShopOwner)
admin.site.register(WorkShop)
admin.site.register(location)
admin.site.register(CarOwner)
admin.site.register(Cars)
admin.site.register(workshopBrands)
admin.site.register(Specialist)
admin.site.register(TowCarOwner)
admin.site.register(City)
admin.site.register(Product)
admin.site.register(PartSupplier)
admin.site.register(Request)
admin.site.register(ProductPartSupplier)
admin.site.register(CarModel)
admin.site.register(TowOrigin)
admin.site.register(TowBrand)
admin.site.register(TowCars)
admin.site.register(Store)
admin.site.register(storeBrands)
admin.site.register(Images)
admin.site.register(Status)
admin.site.register(TransactionStatus)
admin.site.register(RequestType)
admin.site.register(maintenance)
admin.site.register(TowRequest)
# Register your models here.
