from django.contrib import admin
from . models import User, origin, TowCarOwner, Store, storeBrands, Images, Brand, WorkShop, WorkShopOwner, TowCars, TowBrand, TowOrigin, CarModel, location, CarOwner, Product, PartSupplier, ProductPartSupplier, Cars, Specialist, workshopBrands, location, City, Request

admin.site.register(User)
admin.site.register(origin)
admin.site.register(Brand)
admin.site.register(WorkShopOwner)
admin.site.register(WorkShop)
admin.site.register(location)
admin.site.register(CarOwner)
admin.site.register(Cars)
admin.site.register(workshopBrands)
admin.site.register(Specialist)
admin.site.register(TowCarOwner)
admin.site.register(City)
admin.site.register(Product)
admin.site.register(PartSupplier)
admin.site.register(Request)
admin.site.register(ProductPartSupplier)
admin.site.register(CarModel)
admin.site.register(TowOrigin)
admin.site.register(TowBrand)
admin.site.register(TowCars)
admin.site.register(Store)
admin.site.register(storeBrands)
admin.site.register(Images)
# Register your models here.
