# Generated by Django 4.2.7 on 2024-01-03 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='towcar',
            name='userId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.towcarowner'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productpartsupplier',
            name='partSupplierId',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.partsupplier'),
        ),
    ]
