# Generated by Django 4.2.7 on 2023-11-16 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='WorkShopId',
            new_name='workshopId',
        ),
        migrations.RenameField(
            model_name='workshop',
            old_name='WorkShopOwnerId',
            new_name='workshopOwnerId',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
    ]
