# Generated by Django 4.2.7 on 2023-12-22 16:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplierId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.partsupplier'),
            preserve_default=False,
        ),
    ]
