# Generated by Django 4.2.7 on 2024-01-15 15:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_alter_product_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsupplier',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.origin'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.specialist'),
            preserve_default=False,
        ),
    ]
