# Generated by Django 4.2.7 on 2024-02-26 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
