# Generated by Django 4.2.7 on 2023-12-23 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_product_supplierid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='user_Cars',
            new_name='userId',
        ),
    ]
