# Generated by Django 4.2.7 on 2024-01-25 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_remove_towcars_car_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='towcars',
            name='car_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.cars'),
            preserve_default=False,
        ),
    ]
