# Generated by Django 4.2.7 on 2023-11-17 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0002_rename_workshopid_request_workshopid_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
