# Generated by Django 4.2.7 on 2023-12-23 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_rename_user_cars_carowner_userid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='userId',
            new_name='user_id',
        ),
    ]
