# Generated by Django 4.2.7 on 2024-01-15 15:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_partsupplier_brand_partsupplier_origin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsupplier',
            name='brand',
        ),
    ]
