# Generated by Django 4.2.7 on 2024-02-26 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_alter_product_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towcars',
            name='location',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
