# Generated by Django 4.2.7 on 2024-01-25 20:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0003_towcars_car_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towcars',
            name='car_id',
        ),
    ]
