# Generated by Django 4.2.7 on 2023-12-24 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0004_rename_userid_carowner_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='password',
            field=models.CharField(max_length=128, verbose_name='password'),
        ),
    ]
