# Generated by Django 4.2.7 on 2023-11-17 10:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0004_user_usernames_alter_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='usernames',
            new_name='userName',
        ),
    ]
