# Generated by Django 4.2.7 on 2024-01-15 15:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0004_remove_partsupplier_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpartsupplier',
            old_name='brand',
            new_name='brands',
        ),
    ]
