# Generated by Django 4.2.7 on 2024-02-26 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0004_alter_towcars_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='autocare/images'),
        ),
    ]
