# Generated by Django 4.2.7 on 2024-01-26 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0005_alter_cars_platenumber_alter_towcars_platenumber'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='specialistName',
            new_name='specialist',
        ),
    ]
