# Generated by Django 4.2.7 on 2023-12-25 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0005_alter_user_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='user_type',
            field=models.CharField(default='CarOwner', max_length=20),
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='user_type',
            field=models.CharField(default='PartsSupplier', max_length=20),
        ),
        migrations.AddField(
            model_name='towcarowner',
            name='user_type',
            field=models.CharField(default='TowCarOwner', max_length=20),
        ),
        migrations.AddField(
            model_name='workshopowner',
            name='user_type',
            field=models.CharField(default='WorkShopOwner', max_length=20),
        ),
    ]
