# Generated by Django 4.2.7 on 2024-02-26 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0005_alter_workshop_logo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartsupplier',
            name='CarModel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.carmodel'),
        ),
    ]
