# Generated by Django 4.2.7 on 2023-11-18 16:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0005_rename_usernames_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='type',
            new_name='category',
        ),
        migrations.AddField(
            model_name='request',
            name='status',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='request',
            name='userId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
