# Generated by Django 4.2.7 on 2023-12-01 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0006_rename_type_request_category_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cars',
            name='avatar',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='avatar',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
        migrations.AddField(
            model_name='workshop',
            name='portfolio',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
    ]
