# Generated by Django 4.2.7 on 2023-12-26 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0006_carowner_user_type_partsupplier_user_type_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='carowner',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='partsupplier',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='towcarowner',
            name='user_type',
        ),
        migrations.RemoveField(
            model_name='workshopowner',
            name='user_type',
        ),
        migrations.AddField(
            model_name='user',
            name='user_type',
            field=models.CharField(default='Car Owner', max_length=30),
            preserve_default=False,
        ),
    ]
