# Generated by Django 4.2.7 on 2023-12-01 16:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0007_cars_avatar_workshop_avatar_workshop_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='carowner',
            name='favorite',
            field=models.ManyToManyField(blank=True, related_name='favorite', to='autocare.workshop'),
        ),
    ]
