# Generated by Django 4.2.7 on 2024-03-01 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0007_request_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towrequest',
            name='cost',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=30, null=True),
        ),
    ]
