# Generated by Django 4.2.7 on 2023-12-26 16:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0007_remove_carowner_user_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='TowCar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blateNumber', models.CharField(max_length=10)),
                ('carId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.cars')),
                ('coverageCity', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.city')),
            ],
        ),
    ]
