# Generated by Django 4.2.7 on 2023-12-09 11:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0008_carowner_favorite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='portfolio',
        ),
    ]
