# Generated by Django 4.2.7 on 2024-01-27 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0008_storebrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsupplier',
            name='origin',
        ),
    ]
