# Generated by Django 4.2.7 on 2023-12-26 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0008_city_towcar'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towcar',
            name='blateNumber',
        ),
    ]
