# Generated by Django 4.2.7 on 2024-01-27 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0009_remove_partsupplier_origin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='brand',
        ),
    ]
