# Generated by Django 4.2.7 on 2023-12-09 11:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0009_remove_workshop_portfolio'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkShopImages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('portfolio', models.ImageField(null=True, upload_to='autocare/workshop/images')),
                ('WorkShop', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.workshop')),
            ],
        ),
    ]
