# Generated by Django 4.2.7 on 2024-01-28 17:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0010_remove_store_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsupplier',
            name='address',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='avatar',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='contactNumber',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='locationId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.location'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='origin',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.origin'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='storeName',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
