# Generated by Django 4.2.7 on 2023-12-09 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0010_workshopimages'),
    ]

    operations = [
        migrations.RenameField(
            model_name='carowner',
            old_name='userCars',
            new_name='user_Cars',
        ),
    ]
