# Generated by Django 4.2.7 on 2023-12-27 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0010_rename_carid_towcar_car_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='productImage',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
    ]
