# Generated by Django 4.2.7 on 2023-12-29 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0011_alter_product_productimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='available',
            field=models.CharField(default=True, max_length=255),
            preserve_default=False,
        ),
    ]
