# Generated by Django 4.2.7 on 2024-01-28 18:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0011_partsupplier_address_partsupplier_avatar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebrands',
            name='partSupplierId',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.CASCADE, to='autocare.partsupplier'),
            preserve_default=False,
        ),
    ]
