# Generated by Django 4.2.7 on 2023-12-30 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0012_product_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='address',
            field=models.CharField(default='damascus', max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='available',
            field=models.BooleanField(default=True),
        ),
    ]
