# Generated by Django 4.2.7 on 2024-01-28 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0012_storebrands_partsupplierid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storebrands',
            name='store',
        ),
    ]
