# Generated by Django 4.2.7 on 2023-12-10 07:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0012_alter_user_age'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='userName',
        ),
    ]
