# Generated by Django 4.2.7 on 2023-12-30 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0013_workshop_address_alter_product_available'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='supplierId',
        ),
        migrations.RemoveField(
            model_name='productpartsupplier',
            name='user_id',
        ),
        migrations.AddField(
            model_name='productpartsupplier',
            name='partSupplierId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.partsupplier'),
            preserve_default=False,
        ),
    ]
