# Generated by Django 4.2.7 on 2023-12-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0014_workshopbrands'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='brands',
        ),
        migrations.AddField(
            model_name='workshop',
            name='brands',
            field=models.ManyToManyField(to='autocare.brand'),
        ),
    ]
