# Generated by Django 4.2.7 on 2024-02-01 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0014_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='partsupplier',
            name='logo',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
    ]
