# Generated by Django 4.2.7 on 2023-12-30 14:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0014_remove_product_supplierid_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='request',
            old_name='category',
            new_name='requestType',
        ),
        migrations.RemoveField(
            model_name='product',
            name='price',
        ),
        migrations.RemoveField(
            model_name='towrequest',
            name='TowCarOwnerId',
        ),
        migrations.AddField(
            model_name='productpartsupplier',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.brand'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpartsupplier',
            name='count',
            field=models.PositiveIntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='productpartsupplier',
            name='price',
            field=models.DecimalField(decimal_places=4, default=0, max_digits=19),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='request',
            name='notes',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='towrequest',
            name='requestId',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.request'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='autocare.specialist'),
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(default='pendeing', max_length=255),
            preserve_default=False,
        ),
    ]
