# Generated by Django 4.2.7 on 2024-02-09 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0015_partsupplier_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsupplier',
            name='locationId',
        ),
        migrations.AddField(
            model_name='partsupplier',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
