# Generated by Django 4.2.7 on 2024-01-01 06:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0016_alter_productpartsupplier_partsupplierid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productpartsupplier',
            name='partSupplierId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
