# Generated by Django 4.2.7 on 2023-12-20 15:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0016_specialist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='specialist',
        ),
        migrations.AddField(
            model_name='workshop',
            name='specialistName',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.specialist'),
            preserve_default=False,
        ),
    ]
