# Generated by Django 4.2.7 on 2023-12-20 15:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0017_remove_workshop_specialist_workshop_specialistname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='brands',
        ),
    ]
