# Generated by Django 4.2.7 on 2024-02-09 20:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0017_alter_workshop_locationid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='workshop',
            old_name='locationId',
            new_name='location',
        ),
    ]
