# Generated by Django 4.2.7 on 2024-02-12 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0018_rename_locationid_workshop_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='logo',
            field=models.ImageField(null=True, upload_to='autocare/images'),
        ),
    ]
