# Generated by Django 4.2.7 on 2023-12-20 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0018_remove_workshop_brands'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workshop',
            name='currentCars',
            field=models.IntegerField(default=1),
        ),
    ]
