# Generated by Django 4.2.7 on 2024-02-12 17:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0019_workshop_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='towcars',
            name='avatar',
        ),
        migrations.RemoveField(
            model_name='towcars',
            name='carColor',
        ),
    ]
