# Generated by Django 4.2.7 on 2023-12-22 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0019_alter_workshop_currentcars'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='partsupplier',
            name='productId',
        ),
        migrations.CreateModel(
            name='ProductPartSupplier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('productId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='autocare.product')),
                ('user_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='autocare.partsupplier')),
            ],
        ),
    ]
