# Generated by Django 4.2.7 on 2024-02-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0021_towcars_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towcars',
            name='available',
            field=models.BooleanField(default=False),
        ),
    ]
