# Generated by Django 4.2.7 on 2024-02-16 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0022_alter_towcars_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='workshop',
            name='brand',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.brand'),
            preserve_default=False,
        ),
    ]
