# Generated by Django 4.2.7 on 2024-02-16 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0023_workshop_brand'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workshop',
            name='brand',
        ),
    ]
