# Generated by Django 4.2.7 on 2024-02-17 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0024_remove_workshop_brand'),
    ]

    operations = [
        migrations.RenameField(
            model_name='partsupplier',
            old_name='avatar',
            new_name='storeAvatar',
        ),
    ]
