# Generated by Django 4.2.7 on 2024-02-19 08:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0025_rename_avatar_partsupplier_storeavatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='storebrands',
            name='carModel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.carmodel'),
            preserve_default=False,
        ),
    ]
