# Generated by Django 4.2.7 on 2024-02-19 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0026_storebrands_carmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
