# Generated by Django 4.2.7 on 2024-02-19 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0027_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkup',
            name='ends',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='checkup',
            name='starts',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='ends',
            field=models.DateTimeField(null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='starts',
            field=models.DateTimeField(null=True),
        ),
    ]
