# Generated by Django 4.2.7 on 2024-02-19 11:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0029_status_transactionstatus_towrequest_currentlocation_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RequestType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default='PENDING', on_delete=django.db.models.deletion.CASCADE, to='autocare.status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='transactionStatus',
            field=models.ForeignKey(default='INITIATED', on_delete=django.db.models.deletion.CASCADE, to='autocare.transactionstatus'),
        ),
    ]
