# Generated by Django 4.2.7 on 2024-02-19 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0030_requesttype_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(null=True),
        ),
    ]
