# Generated by Django 4.2.7 on 2024-02-19 11:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0031_alter_request_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
