# Generated by Django 4.2.7 on 2024-02-20 11:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0032_alter_request_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='autocare.status'),
        ),
        migrations.AlterField(
            model_name='request',
            name='transactionStatus',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='autocare.transactionstatus'),
        ),
    ]
