# Generated by Django 4.2.7 on 2024-02-20 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0033_maintenance_cost_alter_request_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='maintenance',
            name='description',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
