# Generated by Django 4.2.7 on 2024-02-21 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0034_maintenance_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storebrands',
            old_name='partSupplierId',
            new_name='partSupplier_id',
        ),
    ]
