# Generated by Django 4.2.7 on 2024-02-21 13:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0035_rename_partsupplierid_storebrands_partsupplier_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productpartsupplier',
            old_name='partSupplierId',
            new_name='partSupplier_id',
        ),
    ]
