# Generated by Django 4.2.7 on 2024-02-21 13:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0036_rename_partsupplierid_productpartsupplier_partsupplier_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='towcars',
            name='location',
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
    ]
