# Generated by Django 4.2.7 on 2024-02-22 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0037_towcars_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='workshopId',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='autocare.workshop'),
        ),
    ]
