# Generated by Django 4.2.7 on 2024-02-22 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0039_remove_towrequest_towcarlocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='towrequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
