# Generated by Django 4.2.7 on 2024-02-22 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0042_alter_towrequest_cost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='towrequest',
            name='cost',
            field=models.DecimalField(decimal_places=2, max_digits=30),
        ),
    ]
