# Generated by Django 4.2.7 on 2024-02-25 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autocare', '0046_alter_request_userid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maintenance',
            name='ends',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='maintenance',
            name='starts',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
